Draft of the Echo Handler.
UCLA-CS130/Caviar-Hacker-Grid pull request #35
Opened 2017-02-22 22:18 UTC by avikbmohan

2017-02-22 23:02 UTC, ghost reviewed
Request,Repsonse and handlers should be put into different files.

2017-02-22 23:39 UTC, richardmin97 commented on server/request_handler.cc
> +  /*  m_uri_prefix_ = uri_prefix;
Why is this code commented out? Regardless, don't merge commented out code.

2017-02-22 23:40 UTC, richardmin requested changes
Add tests.

2017-02-22 23:40 UTC, richardmin97 commented on server/request_handler.h
> +class EchoHandler: public RequestHandler {
Make a separate file for this.

2017-02-22 23:40 UTC, richardmin97 commented on server/request_handler.h
> +  enum Status {
You don't have to overwrite the enum.

2017-02-22 23:40 UTC, richardmin97 commented on server/request_handler.h
> +  Status Init(const std::string& uri_prefix,
I *believe* you don't have to redeclare functions if you're overriding them.

2017-02-23 05:41 UTC, richardmin requested changes
There are merge conflicts here?

It's very hard to understand what's going on right now.

2017-02-23 06:20 UTC, richardmin97 commented
Out of date.

2017-02-23 06:20 UTC, closed without merging